config/routes.rb
Rails.application.routes.draw do

  resources :templates
  get "/templates/new/:type" => "templates#new", as: "new_template_type"

  scope "(:locale)", locale: /en|sp|fr/ do
    devise_for :users

    resources :coupen_types, :deal_types, :education_types, :sale_types, :coupens, :banners, :zones

    resources :categories do 
      resources :sub_categories
    end

    resources :institutes do
      resources :branches
    end

    resources :stores do
      resources :branches
    end

    resources :tutorials do
      member do
        get 'complete_order'
      end
    end

    resources :sales do
      member do
        get 'complete_order'
      end
    end

    resources :video_advs do
      member do
        get 'complete_order'
      end
    end

    resources :flyers do
      member do
        get 'complete_order'
      end
    end

    resources :educations do
      member do
        get 'complete_order'
      end
    end

    resources :deals do
      member do
        get 'complete_order'
      end
    end

    resources :advertisements do
      member do
        get 'complete_order'
      end
    end

    get 'home/index'
    get 'search/result' => "home#search_result"
    get '/modal/:id/:model' => "home#data_modal", as: "data_modal"
    post '/mail/:id/:model' => "home#data_emailable", as: "data_emailable"

    post 'search/result' => "home#search_result"
    get '/category_sub' => 'home#category_sub'
    get '/get_store' => 'home#get_store'
    get '/get_institute' => 'home#get_institute'
    get '/get_zone' => 'home#get_zone'
    get '/get_city' => 'home#get_city'
    get '/get_zip' => 'home#get_zip'
    get '/users' => 'home#users'
    get '/block_user/:id' => 'home#block_user', as: "block_user"
    get '/slider/update_content' => 'slider#update_content', as: "update_slider_content"
    get '/session/change_country' => 'home#change_session_country'
    

    get "/:id" => "stores#show", as: "store_show"
    get 'user/:username' => "home#profile", as: "profile"
  end
  get '/:locale' => 'home#index'
  root 'home#index'

end

app/models/store.rb
class Store < ActiveRecord::Base
	belongs_to :user

	has_many :branches, :as => :branchable, dependent: :destroy
	accepts_nested_attributes_for :branches
	
	has_many :store_sub_categories, dependent: :destroy
	has_many :sub_categories, :through => :store_sub_categories

	has_attached_file :image, :styles => {:thumbnail => "550x380>",:thumbnail => "500x380>", :medium => "300x300>", :thumb => "100x100>", :tiny=>"50x50>" }, :default_url => "default-logo.jpg"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  	scope :within_country, lambda {|country| joins(:branches).where("branches.country"=> country) }

  	def self.all_sub_categories
  	 	all.collect(&:sub_categories).flatten.uniq
  	end
  	
  	def to_param
	    "#{id}-#{name}"
	  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.within_country(session[:country])
    @categories = @stores.all_sub_categories.group_by(&:category)

    if params["category_id"].present? || params["sub_category_id"].present?
      @stores = params["category_id"].present? ? Category.find(params["category_id"]).get_stores : SubCategory.find(params["sub_category_id"]).stores
    elsif params["store_id"].present? || (params[:location].present? && params[:location].values.reject(&:empty?).present?)
      store = Store.find(params["store_id"]) if params["store_id"].present?
      branches = store.present? ? (params[:location].values.reject(&:empty?).present? ? store.branches.where(country: session[:country]).in_location(params[:location]) : store.branches.where(country: session[:country], branchable_type: "Store")) : Branch.where(country: session[:country], branchable_type: "Store").in_location(params[:location])
      @stores = branches.collect(&:branchable)
    end
    @stores = @stores.flatten.uniq.paginate(:page => params[:page], :per_page => 12)
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @categories =  @store.sub_categories.collect(&:category).uniq

    if params["branch_id"].present?
      branch = Branch.find(params["branch_id"])
      @advertisements = branch.advertisements.merge(BranchConnect.if_checked)
      @deals = branch.deals.merge(BranchConnect.if_checked)
      @sales = branch.sales.merge(BranchConnect.if_checked)
      @flyers = branch.flyers.merge(BranchConnect.if_checked)
      @video_advs = branch.video_advs.merge(BranchConnect.if_checked)
      @coupens = branch.coupens.merge(BranchConnect.if_checked)
    else
      @advertisements = @store.branches.collect{ |a| a.advertisements.merge(BranchConnect.if_checked)}.flatten.uniq
      @deals = @store.branches.collect{ |a| a.deals.merge(BranchConnect.if_checked)}.flatten.uniq
      @sales = @store.branches.collect{ |a| a.sales.merge(BranchConnect.if_checked)}.flatten.uniq
      @flyers = @store.branches.collect{ |a| a.flyers.merge(BranchConnect.if_checked)}.flatten.uniq
      @video_advs = @store.branches.collect{ |a| a.video_advs.merge(BranchConnect.if_checked)}.flatten.uniq
      @coupens = @store.branches.collect{ |a| a.coupens.merge(BranchConnect.if_checked)}.flatten.uniq
    end

    @hash = Gmaps4rails.build_markers(@store.branches) do |branch, marker|
      coordinates = Geocoder.coordinates(branch.zip)
      if coordinates.present?
        marker.lat coordinates[0]
        marker.lng coordinates[1]
        marker.title branch.name
      end
    end

  end

  # GET /stores/new
  def new
    @store = current_user.stores.build
    @store.branches.build
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = current_user.stores.new(store_params)

    respond_to do |format|
      if @store.save
        params["sub_categories_id"].split(",").each {|sub_category_id| @store.store_sub_categories.create(sub_category_id: sub_category_id)}
        format.html { redirect_to profile_path(locale: I18n.locale,username: @store.user.username), notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        if params["sub_categories_id"].present? 
          @not_required = @store.sub_categories.collect {|s| s.id.to_s} - params["sub_categories_id"].split(",")
          @not_required.each {|sub_category_id| @store.store_sub_categories.where(sub_category_id:  sub_category_id).destroy_all}
          params["sub_categories_id"].split(",").each {|sub_category_id| @store.store_sub_categories.create(sub_category_id: sub_category_id) if !@store.sub_categories.collect {|s| s.id.to_s}.include? sub_category_id}
        end
        format.html { redirect_to profile_path(locale: I18n.locale,username: @store.user.username), notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit!
    end
end

app/views/stores/_form.html.erb
<%= form_for(@store, url: (@store.new_record? ? stores_path : store_path(I18n.locale, @store)) , multipart: true) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-8 form-group">
      <%= f.label :name, "Store Name" %><br>
      <%= f.text_field :name, :placeholder=>"Enter Store Name", required: true, :class=>"form-control" %><br>

      <%= f.label :sub_categories, "Category" %><br>
      <%= text_field_tag "sub_categories_id", "", "data-pre" => @store.sub_categories.map {|f| {:id=> f.id, :name=> "#{f.name}-#{f.category.name}"} }.to_json  %>
      <p class="category-warning error_message"></p>
    </div>

    <div class="col-md-4 form-group">
      <div class="upload-preview">
        <% if @store.id.present? %>
          <%= image_tag @store.image.url(:medium), :style=>"height: 140px; width: 90%;" %>
        <% else %>
          <%= image_tag "missing.png", :style=>"height: 140px; width: 90%;" %>
        <% end %>
      </div>
      <% if @store.id.present? %>
        <%= f.file_field :image %>
      <% else %>
        <%= f.file_field :image %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :placeholder=>"Give a brief Description about your Store", required: true, :class=>"form-control" %><br>
  </div>


  <div class="branches_form">
    <%= render "branches/form", :f => f %>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-success pull-right" %>
  </div>
<% end %>


<script>
  $(function() {
    $("#sub_categories_id").tokenInput("/category_sub.json", {
      preventDuplicates: true,
      prePopulate: $("#sub_categories_id").data("pre"),
      theme: "facebook"
    });
  });

  $('#new_store').submit(function(){
    category=$('#sub_categories_id').val(); 

    if (category==""){
      $('.category-warning').html('Please select category.');
      return false;
    }
    else{
      $('.category-warning').html('');
    } 

  })


  var preview = $(".upload-preview img");
  $("#store_image").change(function(event){
     var input = $(event.currentTarget);
     var file = input[0].files[0];
     var reader = new FileReader();
     reader.onload = function(e){
         image_base64 = e.target.result;
         preview.attr("src", image_base64);
     };
     reader.readAsDataURL(file);
  });

</script>

app/views/stores/_index.html.erb
<br/>
<%= link_to 'New Store', new_store_path, :class=>"btn btn-info pull-right" if user_signed_in? && @user == current_user %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Branches</th>
      <% if (user_signed_in? && (@stores.collect(&:user).include? current_user)) %><th colspan="3"></th><% end %>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td>
          <% store.sub_categories.each do |sub_category| %>
            <%= sub_category.name %> - <%= sub_category.category.name%><br/>
          <% end %>
        </td>
        <td><%= store.branches.count %></td>
        <% if user_signed_in? && store.user == current_user %>
          <td><%= link_to 'Show', store %></td>
          <td><%= link_to 'Edit', edit_store_path(store) %></td>
          <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stores/_index_list.html.erb
<br/>
<%= link_to 'New Store', new_store_path(locale: I18n.locale), :class=>"btn btn-info pull-right" if user_signed_in? && (current_user.is_admin || @user == current_user) %>

<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th></th>
      <% if @user.is_admin %><th><%= t(:owner) %></th> <% end %>
      <th>Name</th>
      <th>Category</th>
      <th>Branches</th>
      <% if (user_signed_in? && (current_user.is_admin || (@stores.collect(&:user).include? current_user))) %><th></th><% end %>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= image_tag store.image.url(:tiny), :class=>"#{'missing_tiny_image' if store.image_file_name.nil? }" %></td>
        <% if @user.is_admin %><td> <%= link_to store.user.name, profile_path(locale: I18n.locale,username: store.user.username) %> </td> <% end %>
        <td><%= store.name %></td>
        <td>
          <% store.sub_categories.each do |sub_category| %>
            <%= sub_category.name %> - <%= sub_category.category.name%><br/>
          <% end %>
        </td>
        <td>
          <% store.branches.each do |branch| %>
            <%= branch.name %> | <%= branch.country %><br/>
          <% end %>
        </td>
        <% if user_signed_in? && (current_user.is_admin || store.user == current_user) %>
          <td><%= link_to 'Show', store_show_path(store, locale: I18n.locale) %>
          <%= link_to t(:edit), edit_store_path(store, locale: I18n.locale) %>
          <%= link_to t(:destroy), [store, locale: I18n.locale] , method: :delete, data: { confirm: 'Are you sure?' } %><br/>
          <%= link_to "Add More Branch", new_store_branch_path(locale: I18n.locale, store_id: store.id) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stores/_store.html.erb
<div class="col-md-3 store_boxes">
	<% cache store do %>
		<%= link_to(image_tag(store.image.url(:medium), :class=>"img-responsive index_box_image"), store_show_path(store, locale: I18n.locale))%>	
		<strong class="text_center"><%= store.name.truncate(20) %></strong>
	<% end %>
</div>

app/views/stores/edit.html.erb
<h2>Editing store</h2>

<%= render 'form' %>

<%= link_to 'Back', profile_path(locale: I18n.locale,:username => @store.user.username), :class=>"btn btn-default" %>

app/views/stores/index.html.erb
<div class="load">
	<%= image_tag "loading.gif" %>
</div>

<div class="row">
	<div class="col-md-3">
		<div class="panel-group" id="accordion">
			<% @categories.each do |category, sub_categories| %>
			  <div class="panel panel-default">
			    <div class="panel-heading">
			      <h4 class="panel-title">
			        <%= link_to category.name, stores_path(locale: I18n.locale, category_id: category.id), remote: true, :class=> "category_search" %>
			        <a data-toggle="collapse" data-parent="#accordion" href="#category_<%= category.id %>" style="float:right">
			        	<%= image_tag "down_arrow.png", :class=>"down_arrow" %>
			        </a>
			      </h4>
			    </div>
			    <div id="category_<%= category.id %>" class="panel-collapse collapse">
			      <div class="panel-body">
			        <ul class="list-group">
						<% sub_categories.each do |sub_category| %>
							  <li class="list-group-item">
							    <%= link_to sub_category.name, stores_path(locale: I18n.locale, sub_category_id: sub_category.id), remote: true, :class=> "category_search"%>
							  </li>
						<% end %>
					</ul>
			      </div>
			    </div>
			  </div>
			<% end %>
		</div>

		<div class="filter_box">
			<%= form_tag stores_path(locale: I18n.locale), :method=> "get", :class=>"filter_form", remote: true do %>
				<h4><%= t(:filter_by) %> : </h4>
				<h5><%= t(:store) %></h5><%= text_field_tag "store_id" %><br/>
				<h5><%= t(:city) %></h5><%= text_field_tag "location[city]", "", :class=>"form-control" %><br/>
				<h5>ZIP</h5><%= text_field_tag "location[zip]", "", :class=>"form-control" %><br/>
				<%= submit_tag t(:submit), :class=>"btn btn-success" %>
			<% end %>
		</div>
	</div>
	<div class="col-md-9">
		<div class="row" >
	      <div class="store_block">
	        <%= render @stores %>
	      </div>
	    </div>
	    <% if !@stores.next_page.nil? %>
	      <div class="load-more-container">
	        <%= image_tag "loading1.gif", style: "display:none;", class: "loading-gif" %>
	        <%= link_to t(:load_more), stores_path(locale: I18n.locale, page: 2), class: "btn btn-primary btn-lg adv-load-more" %>
	      </div>
	    <% end %>
	</div>
</div>




<script>
	$(".filter_form").submit(function(){
		if (($("#store_id").val() != "") || ($("#location").val() != "") ){
			$(".load").show()
		}
	})

	$(".category_search").click(function(){
		$(".load").show()
	})

	$(function() {
    $("#store_id").tokenInput("/get_store.json", {
    	tokenLimit: 1
    });
    $("#location_city").tokenInput("/get_city.json", {
    	tokenLimit: 1
    });
    $("#location_zip").tokenInput("/get_zip.json", {
    	tokenLimit: 1
    });
  });

  $(document).ready(function () {
    // when the load more link is clicked
    $('a.adv-load-more').click(function () {
      $('.adv-load-more').hide();
      $('.loading-gif').show();

      $.ajax({
        type: "GET",
        url: $(this).attr('href'),
        dataType: "script"
      });
      return false;
    });
  });

</script>

app/views/stores/index.js.erb
$(".load").hide();
var page = <%= params[:page].present? ? params[:page] : 1 %>

var category_id = "<%= params[:category_id].present? ? params[:category_id] : '' %>"
var sub_category_id = "<%= params[:sub_category_id].present? ? params[:sub_category_id] : '' %>"
var store_id = "<%= params[:store_id].present? ? params[:store_id] : '' %>"
var location_city = "<%= params[:location].present? ? params[:location][:city] : '' %>"
var location_zip = "<%= params[:location].present? ? params[:location][:zip] : '' %>"


<% if params[:page].present? %>
	$('.store_block').append('<%= j render @stores %>')
<% else %>
	$(".store_block").html("<%= j render @stores %>");
<% end %>

$("a.adv-load-more").attr("href", "/stores?page="+(page+1)+"&category_id="+category_id+"&sub_category_id="+sub_category_id+"&store_id="+store_id+"&location[city]="+location_city+"&location[zip]="+location_zip )
$( ".filter_form input" ).prop( "disabled", false );

// show our load more link
$('.loading-gif').hide();

<% if !@stores.next_page.nil? %>
	$('.adv-load-more').show();
<% else %>
	$('.adv-load-more').hide();
<% end %>

app/views/stores/new.html.erb
	<h2>New store</h2>

	<%= render 'form' %>

app/views/stores/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<div class="row">
  <div class="col-md-3" style="padding:15px">
    <%= image_tag @store.image.url(:medium), :class=>"store_show_image" %>
  </div>
  <div class="col-md-9">
    <h1 class="pull-left"><%= @store.name %></h1><br/><br/><br/><br/>
    <p><%= @store.description %></p>
  </div>
</div>


<div class="row">
  <div class="col-md-3">
    <div class="panel-group" id="accordion">
      <% @categories.each do |category| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <a data-toggle="collapse" data-parent="#accordion" href="#category_<%= category.id %>" >
              <h4 class="panel-title">
                <%= category.name %>
                <%= image_tag "down_arrow.png", :class=>"down_arrow pull-right" %>
              </h4>
            </a>
          </div>
          <div id="category_<%= category.id %>" class="panel-collapse collapse">
            <div class="panel-body">
              <ul class="list-group">
                <% category.sub_categories.each do |sub_category| %>
                  <% if sub_category.stores.include? @store %>
                    <li class="list-group-item">
                      <%= sub_category.name %>
                    </li>
                  <% end %>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <ul class="list-group">
      <% @store.branches.each do|branch| %>
        <li class="list-group-item">
          <h4><%= link_to branch.name, store_show_path(locale: I18n.locale,branch_id: branch.id), remote: true %></h4>
          <%= branch.city %> | <%= branch.country %>
          <%= link_to 'Delete', store_branch_path(I18n.locale, @store.id, branch.id), method: :delete, :class=>"pull-right", data: { confirm: 'Are you sure?' } if user_signed_in? && @store.user == current_user %>
        </li>
      <% end %>
    </ul>
    <div class="map_div">
      <div id="map" style='width: 262px; height: 225px;'></div>
    </div>
  </div>
  <div class="col-md-9 store_show_block">
    <%= render 'home/result_list' %>
  </div>
</div>


<script type="text/javascript">
  handler = Gmaps.build('Google');

  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/stores/show.js.erb
$(".load").hide();
$(".store_show_block").html("<%= j render 'home/result_list' %>")