config/routes.rb
Rails.application.routes.draw do

  resources :templates
  get "/templates/new/:type" => "templates#new", as: "new_template_type"

  scope "(:locale)", locale: /en|sp|fr/ do
    devise_for :users

    resources :coupen_types, :deal_types, :education_types, :sale_types, :coupens, :banners, :zones

    resources :categories do 
      resources :sub_categories
    end

    resources :institutes do
      resources :branches
    end

    resources :stores do
      resources :branches
    end

    resources :tutorials do
      member do
        get 'complete_order'
      end
    end

    resources :sales do
      member do
        get 'complete_order'
      end
    end

    resources :video_advs do
      member do
        get 'complete_order'
      end
    end

    resources :flyers do
      member do
        get 'complete_order'
      end
    end

    resources :educations do
      member do
        get 'complete_order'
      end
    end

    resources :deals do
      member do
        get 'complete_order'
      end
    end

    resources :advertisements do
      member do
        get 'complete_order'
      end
    end

    get 'home/index'
    get 'search/result' => "home#search_result"
    get '/modal/:id/:model' => "home#data_modal", as: "data_modal"
    post '/mail/:id/:model' => "home#data_emailable", as: "data_emailable"

    post 'search/result' => "home#search_result"
    get '/category_sub' => 'home#category_sub'
    get '/get_store' => 'home#get_store'
    get '/get_institute' => 'home#get_institute'
    get '/get_zone' => 'home#get_zone'
    get '/get_city' => 'home#get_city'
    get '/get_zip' => 'home#get_zip'
    get '/users' => 'home#users'
    get '/block_user/:id' => 'home#block_user', as: "block_user"
    get '/slider/update_content' => 'slider#update_content', as: "update_slider_content"
    get '/session/change_country' => 'home#change_session_country'
    

    get "/:id" => "stores#show", as: "store_show"
    get 'user/:username' => "home#profile", as: "profile"
  end
  get '/:locale' => 'home#index'
  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  include HomeHelper
  def index
    Tracker.all.size == 0 ? Tracker.create.increament_visit_count : Tracker.first.increament_visit_count
    if !session[:country].present?
      @location = GeoIP.new('GeoIP.dat').country(request.ip)
      #<struct GeoIP::Country request="117.212.247.251", ip="117.212.247.251", country_code=103, country_code2="IN", country_code3="IND", country_name="India", continent_code="AS">
      session[:country] = @location.country_code2
    end

    if !session[:category_header].present?
      session[:category_header] = Category.order("name").collect{|c| [c.id, c.name] }
    end

  	advertisements = Advertisement.all.running(session[:country]).flatten.uniq
    @zones_having_data = advertisements.collect{ |a| a.zones.merge(AdvZone.if_checked) }.flatten.uniq.sort_by(&:name)

    split_count = (advertisements.size/3) + 1
    @advertisements = advertisements.each_slice(split_count).to_a


    @deal_types = DealType.limit(4)
    @sale_types = SaleType.limit(2)
    @coupen_types = CoupenType.limit(2)
  	@education_types = EducationType.limit(2)
    @top_banners = Banner.running.where(position: "Top")
    @bottom_banners = Banner.running.where(position: "Bottom")
    @flyers = Flyer.running(session[:country])
    @tutorials = Tutorial.running(session[:country])
    @videos = VideoAdv.running(session[:country])
  end

  def profile
  	@user = User.find_by_username(params[:username])
  	@stores = @user.is_admin ? Store.all : @user.stores
  	@advertisements = @user.is_admin ? Advertisement.all : @user.advertisements
    @deals = @user.is_admin ? Deal.all : @user.deals
    @sales = @user.is_admin ? Sale.all : @user.sales
    @educations = @user.is_admin ? Education.all : @user.educations
    @flyers = @user.is_admin ? Flyer.all : @user.flyers
    @video_advs = @user.is_admin ? VideoAdv.all : @user.video_advs
    @coupens = @user.is_admin ? Coupen.all : @user.coupens
    @institutes = @user.is_admin ? Institute.all : @user.institutes
  	@tutorials = @user.is_admin ? Tutorial.all : @user.tutorials
    @banners = Banner.all if @user.is_admin
  end

  def data_modal
    @data = params[:model].constantize.find(params[:id].to_i)
  end

  def data_emailable
    data = params[:model].constantize.find(params[:id].to_i)
    AdvsMailer.send_advs(params[:email], data).deliver
    render json: {email: params[:email]}
  end

  def category_sub
    @sub_categories = SubCategory.where("lower(name) like ?", "%#{params[:q].downcase}%")
    @categories = Category.where("lower(name) like ?", "%#{params[:q].downcase}%")
    @categories.each do |category|
      @sub_categories << category.sub_categories
    end
    render :json => @sub_categories.flatten.uniq.map {|f| {:id=> f.id, :name=> "#{f.name}-#{f.category.name}"} }
  end

  def get_store
    store = Store.where("lower(name) like ?", "%#{params[:q].downcase}%")
    render :json => store
  end

  def get_institute
    institute = Institute.where("lower(name) like ?", "%#{params[:q].downcase}%")
    render :json => institute
  end

  def get_city
    city = Branch.where("lower(city) like ?", "%#{params[:q].downcase}%").map {|f| {:id=> f.city, :name=> f.city} }
    render :json => city
  end

  def get_zip
    zip = Branch.where("lower(zip) like ?", "%#{params[:q].downcase}%").map {|f| {:id=> f.zip, :name=> f.zip} }
    render :json => zip
  end

  def get_zone
    zone = Zone.where("lower(name) like ?", "%#{params[:q].downcase}%")
    render :json => zone
  end

  def search_result
    @sub_categories = Advertisement.all_sub_categories(session[:country])
    @sub_categories << Deal.all_sub_categories(session[:country])
    @sub_categories << Sale.all_sub_categories(session[:country])
    @sub_categories << Education.all_sub_categories(session[:country])
    @sub_categories << Flyer.all_sub_categories(session[:country])
    @sub_categories << VideoAdv.all_sub_categories(session[:country])
    @sub_categories << Coupen.all_sub_categories(session[:country])
    
    @categories = @sub_categories.flatten.collect(&:category).flatten.uniq

    @advertisements = []
    @deals = []
    @sales = []
    @educations = []
    @flyers = []
    @video_advs = []
    @coupens = []
    @tutorials = []
    branches = []

    if params["category_id"].present? || params["sub_category_id"].present?
      if params["category_id"].present?
        @category = Category.find(params["category_id"])
        stores = @category.get_stores
        institutes = @category.get_institutes
      else
        @sub_category = SubCategory.find(params["sub_category_id"])
        stores = @sub_category.stores
        institutes = @sub_category.institutes
      end
      stores.each{ |i| branches << search_into_branches(i, params) }
      institutes.each{ |i| branches << search_into_branches(i, params) }

      search_into_everything(params, branches)
    elsif params["search"].present? || params["location"].present?
      if params["location"].present?
        Store.all.each{ |i| branches << search_into_branches(i, params) }
        Institute.all.each{ |i| branches << search_into_branches(i, params) }
      else
        branches = Branch.all
      end
      search_into_everything(params, branches)

    elsif params["store_id"].present?
      store = Store.find(params["store_id"])
      branches = (params["city"].present? || params["zip"].present?) ? store.branches.in_location(params) : store.branches

      all_branch_related(branches)

    elsif params["city"].present? || params["zip"].present?
      branches = Branch.in_location(params)

      all_branch_related(branches)

    elsif params["city"].present?
      branches = Branch.where("city = ?", params["city"] )
      all_branch_related(branches)

    elsif params["zip"].present?
      branches = Branch.where("zip = ?", params["zip"] )
      all_branch_related(branches)

    else
      @advertisements = Advertisement.all
      @deals = Deal.all
      @sales = Sale.all
      @educations = Education.all
      @flyers = Flyer.all
      @video_advs = VideoAdv.all
      @coupens = Coupen.all
      @tutorials = Tutorial.all
    end

    @advertisements = @advertisements.flatten.uniq
    @deals = @deals.flatten.uniq
    @sales = @sales.flatten.uniq
    @educations = @educations.flatten.uniq
    @flyers = @flyers.flatten.uniq
    @video_advs = @video_advs.flatten.uniq
    @coupens = @coupens.flatten.uniq
    @tutorials = @tutorials.flatten.uniq

  end


  def users
    @users = User.where("id != ?", current_user.id)
  end

  def block_user
    user = User.find(params[:id])
    user.update_attributes(block: (user.block ? false : true))
    redirect_to users_path(locale: I18n.locale)
  end

  def change_session_country
    session[:country] = params[:country_code]
    render json: {url: request.referer }
  end

  def all_branch_related(branches)
    @advertisements = branches.collect(&:advertisements).merge(BranchConnect.if_checked)
    @deals = branches.collect(&:deals).merge(BranchConnect.if_checked)
    @sales = branches.collect(&:sales).merge(BranchConnect.if_checked)
    @educations = branches.collect(&:educations).merge(BranchConnect.if_checked)
    @flyers = branches.collect(&:flyers).merge(BranchConnect.if_checked)
    @video_advs = branches.collect(&:video_advs).merge(BranchConnect.if_checked)
    @coupens = branches.collect(&:coupens).merge(BranchConnect.if_checked)
    @tutorials = branches.collect(&:tutorials).merge(BranchConnect.if_checked)
  end

  def search_into_branches(model, params)
    model.branches.where("lower(address) LIKE ? OR lower(city) LIKE ? OR lower(state) LIKE ? OR lower(country) LIKE ? OR zip LIKE ? ", "%#{params['location'].downcase}%", "%#{params['location'].downcase}%", "%#{params['location'].downcase}%", "%#{params['location'].downcase}%", "%#{params['location'].downcase}%")
  end
end

app/helpers/home_helper.rb
module HomeHelper
	def search_into_everything(params, branches)
	    branches.flatten.each do |branch|
	      @advertisements << branch.advertisements.merge(BranchConnect.if_checked).where("lower(title) LIKE ?", "%#{params['search'].downcase}%")
	      @deals << branch.deals.merge(BranchConnect.if_checked).where("lower(title) LIKE ?", "%#{params['search'].downcase}%")
	      @sales << branch.sales.merge(BranchConnect.if_checked).where("lower(title) LIKE ?", "%#{params['search'].downcase}%")
	      @educations << branch.educations.merge(BranchConnect.if_checked).where("lower(title) LIKE ?", "%#{params['search'].downcase}%")
	      @flyers << branch.flyers.merge(BranchConnect.if_checked).where("lower(title) LIKE ?", "%#{params['search'].downcase}%")
	      @video_advs << branch.video_advs.merge(BranchConnect.if_checked).where("lower(title) LIKE ?", "%#{params['search'].downcase}%")
	      @coupens << branch.coupens.merge(BranchConnect.if_checked).where("lower(title) LIKE ?", "%#{params['search'].downcase}%")
	      @tutorials << branch.tutorials.merge(BranchConnect.if_checked).where("lower(title) LIKE ?", "%#{params['search'].downcase}%")
	    end
	end
end

app/views/home/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-body">
      <%= @data.web_link.present? ? link_to(image_tag(@data.image.url(:thumbnail), :class=>"modal_image", :id=>"image_data_#{@data.id}"), @data.web_link) : (image_tag @data.image.url(:thumbnail), :class=>"modal_image", :id=>"image_data_#{@data.id}") %>
      <br/>
      <br/>
      <div class="row">
        <div class="col-md-3 share_modal">
          Share on :
            <%= image_tag "fb.png", class: "fb_share", id: "banner1~#{@data.id}~#{@data.class}~#{@data.title}~#{@data.image.url}" %>
            <%= social_share_button_tag(@data.title, :url => root_url(locale: I18n.locale, id: @data.id, model: @data.class)) %>
        </div>
        <div class="col-md-2">
          <%= link_to "Print", "#", :class=>"btn btn-default print_me", :id=>"print_data_#{@data.id}" %>
        </div>
        <div class="col-md-7">
          <%= form_tag data_emailable_path(id: @data.id, model: @data.class), remote: true do %>
            <%= text_field_tag "email", "", :placeholder=>"Email whom you  want to send this", class: "form-control pull-left", :style=>"width:68%" %>
            <%= submit_tag "Send Email", :class=> "btn btn-default", data: { disable_with: "Sending..." } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_result_list.html.erb
<% if params["search"].present? || @category.present? || @sub_category.present?  || params["location"].present? %>
	<h3>Search Result for 
		<% if @category.present? %> Category : <%= @category.name %> <% end %>
		<% if @sub_category.present? %> SubCategory : <%= @sub_category.name %> <% end %>
		<% if params["search"].present? %>Title : <%= params['search'] %> <% end %>
		<% if params["location"].present? %> Location : <%= params['location'] %><% end %>
	</h3>
<% end %>
<!-- Nav tabs -->
<% if @advertisements.blank? && @deals.blank? && @sales.blank? && @educations.blank? && @flyers.blank? && @video_advs.blank? && @coupens.blank? %>
	<h3>No Data Present</h3>
<% end %>
<ul class="nav nav-pills" role="tablist">
  <% if !@advertisements.blank? %>
 	  <li class="active"><a href="#Advertisements" role="tab" data-toggle="tab">Biz</a></li>
  <% end %>
  <% if !@deals.blank? %>
  	<li <% if @advertisements.blank? %> class="active" <% end %>><a href="#Deals" role="tab" data-toggle="tab">Deals</a></li>
  <% end %>
  <%# if !@banners.blank? %>
  	<!-- <li <%# if @advertisements.blank? && @deals.blank? %> class="active" <%# end %>><a href="#Banners" role="tab" data-toggle="tab">Banners</a></li> -->
  <%# end %>
  <% if !@sales.blank? %>
  	<li <% if @advertisements.blank? && @deals.blank? %> class="active" <% end %>><a href="#Sales" role="tab" data-toggle="tab">Sales</a></li>
  <% end %>
  <% if !@educations.blank? %>
  	<li <% if @advertisements.blank? && @deals.blank? && @sales.blank? %> class="active" <% end %>><a href="#Educations" role="tab" data-toggle="tab">Educations</a></li>
  <% end %>
  <% if !@flyers.blank? %>
  	<li <% if @advertisements.blank? && @deals.blank? && @sales.blank? && @educations.blank? %> class="active" <% end %>><a href="#Flyers" role="tab" data-toggle="tab">Flyers</a></li>
  <% end %>
  <% if !@video_advs.blank? %>
    <li <% if @advertisements.blank? && @deals.blank? && @sales.blank? && @educations.blank? && @flyers.blank? %> class="active" <% end %>><a href="#Videos" role="tab" data-toggle="tab">Videos</a></li>
  <% end %>
  <% if !@coupens.blank? %>
    <li <% if @advertisements.blank? && @deals.blank? && @sales.blank? && @educations.blank? && @flyers.blank? && @video_advs.blank? %> class="active" <% end %>><a href="#Coupon" role="tab" data-toggle="tab">Coupons</a></li>
  <% end %>
  <% if !@tutorials.blank? %>
    <li <% if @advertisements.blank? && @deals.blank? && @sales.blank? && @educations.blank? && @flyers.blank? && @video_advs.blank?&& @coupens.blank? %> class="active" <% end %>><a href="#tutorial" role="tab" data-toggle="tab">Tutorial</a></li>
  <% end %>
</ul>
<br/>
<div class="tab-content">
  <% if !@advertisements.blank? %>
	  <div class="tab-pane active" id="Advertisements">
	  	<%= render @advertisements %>
	  </div>
  <% end %>
  <% if !@deals.blank? %>
	  <div class="tab-pane <% if @advertisements.blank? %> active <% end %> " id="Deals">
	  	<%= render @deals %>
	  </div>
  <% end %>
  <%# if !@banners.blank? %>
	  <!-- <div class="tab-pane <%# if @advertisements.blank? && @deals.blank? %> active <%# end %> " id="Banners">
	  	<%#= render 'banners/index_box' %>
	  </div> -->
  <%# end %>
  <% if !@sales.blank? %>
	  <div class="tab-pane <% if @advertisements.blank? && @deals.blank? %> active <% end %> " id="Sales">
      <%= render @sales %>
	  </div>
  <% end %>
  <% if !@educations.blank? %>
	  <div class="tab-pane <% if @advertisements.blank? && @deals.blank? && @sales.blank? %> active <% end %> " id="Educations">
      <%= render @educations %>
	  </div>
  <% end %>
  <% if !@flyers.blank? %>
	  <div class="tab-pane <% if @advertisements.blank? && @deals.blank? && @sales.blank? && @educations.blank? %> active <% end %> " id="Flyers"> 
      <%= render @flyers %>
	  </div>
  <% end %>
  <% if !@video_advs.blank? %>
    <div class="tab-pane <% if @advertisements.blank? && @deals.blank? && @sales.blank? && @educations.blank? && @flyers.blank? %> active <% end %> " id="Videos">
      <%= render @video_advs %>
    </div>
  <% end %>
  <% if !@coupens.blank? %>
    <div class="tab-pane <% if @advertisements.blank? && @deals.blank? && @sales.blank? && @educations.blank? && @flyers.blank? && @video_advs.blank? %> active <% end %> " id="Coupon">
      <%= render @coupens %>
    </div>
  <% end %>
  <% if !@tutorials.blank? %>
    <div class="tab-pane <% if @advertisements.blank? && @deals.blank? && @sales.blank? && @educations.blank? && @flyers.blank? && @video_advs.blank? && @coupens.blank? %> active <% end %> " id="tutorial">
      <%= render @tutorials %>
    </div>
  <% end %>
</div>

app/views/home/data_modal.js.erb
$("#myModal").html("<%= escape_javascript(render 'modal') %>");
$('#myModal').modal('show');

app/views/home/index.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<div class="row">
	<div class="col-lg-8 col-sm-8 col-md-8 col-xs-12 no-pd no-mg">
		<div class="row">
			<% @deal_types.each do |deal_type| %>
				<div class="col-md-6" style="margin-bottom: 3px;">
					<div class="thumbnail home_type_header text-center bg-thmb">
						<%= link_to deal_type.name, deals_path(deal_type: [deal_type.id], locale: I18n.locale) %>
					</div>
					<div id="dealtype_<%= deal_type.id %>" class="carousel carousel-fade">
						<%= render "slider/dealtype_slider", deal_type: deal_type %>
					</div>
					<!-- End Carousel -->
				</div>
			<% end %>
		</div>
		<div id="banner1_slider" class="carousel carousel-fade">
			<%= render "slider/banner1_slider" %>
		</div>
		<div id="banner2_slider" class="carousel carousel-fade">
			<%= render "slider/banner2_slider" %>
		</div>
	</div>
	<!--slider-->
	<div class="col-lg-4 col-sm-4 col-md-4 col-xs-12 bdr-side" style="overflow: hidden;">
		<br />
		<div class="thumbnail home_type_header text-center bg-thmb">
			<%= link_to t(:featured_video), video_advs_path(locale: I18n.locale)%>
		</div>
		<div class="flex-video widescreen">
			<div id="video_slider" class="carousel carousel-fade" style="margin-top: -25px !important;">
				<%= render "slider/video_slider" %>
			</div>
		</div>
		<% @coupen_types.each do |coupen_type| %>
			<div class="thumbnail home_type_header text-center bg-thmb">
				<%= link_to coupen_type.name, deals_path(coupen_type: [coupen_type.id], locale: I18n.locale) %>
			</div>
			<div id="coupentype_<%= coupen_type.id %>" class="carousel carousel-fade">
				<%= render "slider/coupentype_slider", coupen_type: coupen_type %>
			</div>
		<% end %>
		<div class="thumbnail home_type_header text-center bg-thmb">
			<%= link_to t(:tutorial_services), tutorials_path(locale: I18n.locale)%>
		</div>
		<div id="tutorial_slider" class="carousel carousel-fade">
			<%= render "slider/tutorial_slider" %>
		</div>
	</div>
</div>
<!--row end-->
<br/>
<div class="row pdrt_0">
	<div class="jumbotron zone_list row">
		<b>
	  <% @zones_having_data.each do |zone| %>
	  	<div class="col-md-1" >
				<%= link_to zone.name, advertisements_path(locale: I18n.locale,zone_id: zone.id) %>
			</div>
		<% end %>
		</b>
	</div>
 	<% @advertisements.each_with_index do |adv_block, index| %>
 		<div class="col-md-4" style="margin-bottom: 20px;">
			<div id="zone_<%= index+1 %>" class="carousel carousel-fade">
				<%= render "slider/zone_slider", advertisements: adv_block %>
			</div>
			<!-- End Carousel -->
		</div>
	<% end %>
</div>
<div class="row">
	<div class="col-md-8">
		<div class="row">
			<% @sale_types.each do |sale_type|%>
				<div class="col-md-6">
					<div class="thumbnail home_type_header text-center bg-thmb">
						<%= link_to sale_type.name, sales_path(sale_type: [sale_type.id], locale: I18n.locale) %>
					</div>
					<div id="saletype_<%= sale_type.id %>" class="carousel-video carousel-fade">
						<%= render "slider/saletype_slider", sale_type: sale_type %>
					</div>
				</div>
			<% end %>
		</div>
		<div class="row">
			<% @education_types.each do |education_type|%>
				<div class="col-md-6">
					<div class="thumbnail home_type_header text-center bg-thmb">
						<%= link_to education_type.name, educations_path(education_type: [education_type.id], locale: I18n.locale) %>
					</div>
					<div id="educationtype_<%= education_type.id %>" class="carousel carousel-fade">
						<%= render "slider/educationtype_slider", education_type: education_type %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
	<div class="col-md-4 bdr-side">
		<br />
		<div class="thumbnail home_type_header text-center bg-thmb">
			<%= link_to t(:store_flyers), flyers_path(locale: I18n.locale)%>
		</div>
		<div id="flyer_slider" class="carousel carousel-fade">
			<%= render "slider/flyer_slider" %>
		</div>
	</div>
</div>
<!--row end-->

<script>
	$(document).ready(function(){
		/* smooth scrolling for scroll to top */
		$('.scroll-top').click(function() {
			$('body,html').animate({ scrollTop: 0 }, 600);
			return false;
		})

		$('.carousel').carousel({
			interval: 5000
		});

		$('.carousel-video').carousel({
			interval: 7000
		});

		$('.carousel').on('slid.bs.carousel', function () {
			var id = this.id
			var data = id.split("_")
	    	slides = $("#"+id+" .item").size();
	    	current = $("#"+id+" .item.active").index()
    		if (slides > 2 && current == slides-1){
				setTimeout(
				  function() 
				  {
				    $.ajax({
		    			type : "GET",
		    			url: "<%= update_slider_content_path(locale: I18n.locale)%>",
		    			data: {data1: data[0], data2: data[1]}
		    		})
				  }, 4000);
    		}
    	}); 

	})

	<% if params[:id].present? && params[:model].present? %>
		$(document).ready(function(){
			$.ajax({
				type: "get",
				url: "<%= data_modal_path(id: params[:id], model: params[:model]) %>"
			})
		})
	<% end %>
</script>

<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js"></script>

<script>
window.fbAsyncInit = function () {
    FB.init({ appId: '1374702796089833', cookie: true, xfbml: true, oauth: true });
}

$(document).on('click','.fb_share', function(){
	var values = this.id.split("~")
    FB.ui(
       {
           method: 'feed',
           link: window.location.host+'?locale='+'<%= I18n.locale %>'+'&id='+values[1]+'&model='+values[2],                    
           name: values[3],
           picture: values[4],
           caption: values[3],
           description: 'Catch this '+ values[2]+ ' on Etcty.com' ,
       });
	});
</script>

app/views/home/search_result.html.erb
<div class="load">
	<%= image_tag "loading.gif" %>
</div>

<div class="row">
	<div class="col-md-3">
		<div class="panel-group" id="accordion">
			<% @categories.each do|category| %>
			  <div class="panel panel-default">
			    <div class="panel-heading">
			      <h4 class="panel-title">
			        <%= link_to category.name, search_result_path(category_id: category.id), remote: true, :class=> "category_search" %>
			        <a data-toggle="collapse" data-parent="#accordion" href="#category_<%= category.id %>" style="float:right">
			        	<%= image_tag "down_arrow.png", :class=>"down_arrow" %>
			        </a>
			      </h4>
			    </div>
			    <div id="category_<%= category.id %>" class="panel-collapse collapse">
			      <div class="panel-body">
			        <ul class="list-group">
						<% category.sub_categories.each do |sub_category| %>
							<% if @sub_categories.include? sub_category %>
							  <li class="list-group-item">
							    <%= link_to sub_category.name, search_result_path(sub_category_id: sub_category.id), remote: true, :class=> "category_search"%>
							  </li>
							<% end %>
						<% end %>
					</ul>
			      </div>
			    </div>
			  </div>
			<% end %>
		</div>

		<div class="filter_box">
			<%= form_tag search_result_path, :class=>"filter_form", remote: true do %>
				<h4><%= t(:filter_by) %> : </h4>
				<h5><%= t(:store) %></h5><%= text_field_tag "store_id" %><br/>
				<h5><%= t(:city) %></h5><%= text_field_tag "city", "", :class=>"form-control" %><br/>
				<h5>ZIP</h5><%= text_field_tag "zip", "", :class=>"form-control" %><br/>
				<%= submit_tag t(:submit) %>
			<% end %>
		</div>
	</div>
	<div class="col-md-9 search_result_block">
		<%= render 'result_list' %>
	</div>
</div>


<script>
	$(".filter_form").submit(function(){
		if (($("#store_id").val() != "") || ($("#city").val() != "") || ($("#zip").val() != "") ){
			$(".load").show()
		}
	})

	$(".category_search").click(function(){
		$(".load").show()
	})

	$(function() {
    $("#store_id").tokenInput("/get_store.json", {
    	tokenLimit: 1
    });
    $("#city").tokenInput("/get_city.json", {
    	tokenLimit: 1
    });
    $("#zip").tokenInput("/get_zip.json", {
    	tokenLimit: 1
    });
  });

</script>

app/views/home/search_result.js.erb
$(".load").hide();
$(".search_result_block").html("<%= j render 'result_list' %>")
$( ".filter_form input" ).prop( "disabled", false );

app/views/home/users.html.erb
<h1>Listing Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Type</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.avatar.url(:tiny), :class=>"missing_tiny_image" %></td>
        <td><%= user.name %></td>
        <td><%= link_to user.username, profile_path(locale: I18n.locale,username: user.username) %></td>
        <td><%= user.email %></td>
        <td><%= user.is_admin ? "Admin" : "User" %></td>        
        <td><%= link_to "#{user.block ? 'Unblock' : 'Block'}", block_user_path(user, locale: I18n.locale) if !user.is_admin %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>