config/routes.rb
Rails.application.routes.draw do

  resources :templates
  get "/templates/new/:type" => "templates#new", as: "new_template_type"

  scope "(:locale)", locale: /en|sp|fr/ do
    devise_for :users

    resources :coupen_types, :deal_types, :education_types, :sale_types, :coupens, :banners, :zones

    resources :categories do 
      resources :sub_categories
    end

    resources :institutes do
      resources :branches
    end

    resources :stores do
      resources :branches
    end

    resources :tutorials do
      member do
        get 'complete_order'
      end
    end

    resources :sales do
      member do
        get 'complete_order'
      end
    end

    resources :video_advs do
      member do
        get 'complete_order'
      end
    end

    resources :flyers do
      member do
        get 'complete_order'
      end
    end

    resources :educations do
      member do
        get 'complete_order'
      end
    end

    resources :deals do
      member do
        get 'complete_order'
      end
    end

    resources :advertisements do
      member do
        get 'complete_order'
      end
    end

    get 'home/index'
    get 'search/result' => "home#search_result"
    get '/modal/:id/:model' => "home#data_modal", as: "data_modal"
    post '/mail/:id/:model' => "home#data_emailable", as: "data_emailable"

    post 'search/result' => "home#search_result"
    get '/category_sub' => 'home#category_sub'
    get '/get_store' => 'home#get_store'
    get '/get_institute' => 'home#get_institute'
    get '/get_zone' => 'home#get_zone'
    get '/get_city' => 'home#get_city'
    get '/get_zip' => 'home#get_zip'
    get '/users' => 'home#users'
    get '/block_user/:id' => 'home#block_user', as: "block_user"
    get '/slider/update_content' => 'slider#update_content', as: "update_slider_content"
    get '/session/change_country' => 'home#change_session_country'
    

    get "/:id" => "stores#show", as: "store_show"
    get 'user/:username' => "home#profile", as: "profile"
  end
  get '/:locale' => 'home#index'
  root 'home#index'

end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :user

	has_many :branch_connects, as: :connectable
	has_many :branches, through: :branch_connects
	accepts_nested_attributes_for :branch_connects
	

	has_many :education_connects, dependent: :destroy
	has_many :education_types, :through => :education_connects
	accepts_nested_attributes_for :education_connects

	has_many :transactions, :as => :purchasable, dependent: :destroy

	has_attached_file :image, :styles => { :thumbnail => "550x380>", :medium => "300x300>", :tiny=>"50x50>" }, :default_url => "missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  	scope :running, lambda {|country| where("start_date <= ? AND end_date >= ?", Date.today, Date.today).order(ActiveRecord::Base.connection.instance_values["config"][:adapter] == "mysql2" ? "RAND()" : "RANDOM()").joins(:branches).where("branches.country"=> country) }

  	def self.all_sub_categories
  		all.collect(&:branches).flatten.uniq.collect(&:branchable).uniq.collect(&:sub_categories).flatten.uniq
  	end

  	def expired?
		self.end_date < Date.today
	end

end

app/models/education_type.rb
class EducationType < ActiveRecord::Base
	has_many :education_connects, dependent: :destroy
	has_many :educations, :through => :education_connects

	default_scope { order('id') }
	translates :name
	default_scope { includes(:translations) }
	
	def educations_within_today(country)
		self.educations.merge(EducationConnect.if_checked).running(country)
	end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy, :complete_order]


	def index
    @educations = Education.running(session[:country])
    @categories = @educations.all_sub_categories.group_by(&:category)

    if params["category_id"].present? || params["sub_category_id"].present?
      institutes = params["category_id"].present? ? Category.find(params["category_id"]).get_institutes : SubCategory.find(params["sub_category_id"]).institutes
      @educations = institutes.collect(&:branches).flatten.collect{ |b| b.educations.running(session[:country])}
    elsif params["institute_id"].present?
      @educations = []
      institute = Institute.find(params["institute_id"])
      branches = (params["city"].present? || params["zip"].present?) ? institute.branches.in_location(params) : institute.branches
      branch_educations(branches)
    elsif params["city"].present? || params["zip"].present?
      @educations = []
      branches = Branch.in_location(params)
      branch_educations(branches)
    elsif params["education_type"].present?
      params["education_type"] = params["education_type"].split(",") if !params["education_type"].kind_of?(Array) 
      @educations = []
      params["education_type"].each do |education_type|
        @educations << EducationType.find(education_type).educations.running(session[:country])
      end
    end

    @educations = @educations.flatten.uniq.paginate(:page => params[:page], :per_page => 12)
  end

  def new
    @education = Education.new
    EducationType.all.each do |a|
      @education.education_connects.build(education_type_id: a.id)
    end

    current_user.institutes.collect(&:branches).flatten.each do |branch|
      @education.branch_connects.build(branch_id: branch.id)
    end

    redirect_to new_institute_path(locale: I18n.locale), notice: "You first have to create a institute before creating banner" if current_user.institutes.blank?
  end


  def create
    @education = current_user.educations.create(education_params)    
    @education.transactions.create(user_id: @education.user_id, amount: params[:amount], currency: "USD", status: "pending")
    # base_url = (Rails.env == "development") ? 'http://localhost:3000' : 'http://www.etcty.com'

    # @response = EXPRESS_GATEWAY.setup_purchase((params[:amount].to_i*100),
    #   return_url: base_url+complete_order_education_path(@education, locale: I18n.locale) ,
    #   cancel_return_url: base_url,
    #   currency: "USD"
    # )

    # redirect_to EXPRESS_GATEWAY.redirect_url_for(@response.token)
    redirect_to complete_order_education_path(@education, locale: I18n.locale)
  end

  def edit
  end

  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to profile_path(locale: I18n.locale,username: @education.user.username), notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(locale: I18n.locale,username: @education.user.username), notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def complete_order
    # response = EXPRESS_GATEWAY.purchase((@education.transactions[0].amount)*100, {:token => params[:token],:payer_id => params[:PayerID]})
    # @education.transactions[0].update_attributes(paypal_token: params[:token], paypal_payer_id: params[:PayerID])
    @education.transactions[0].update_attributes(status: "paid")

    # if response.success?
    #   @education.transactions[0].update_attributes(status: "paid")
    # end
    # flash[:sucess] = response.success? ? "Congratulations, your education has been created" : "Oops!! Problem with the payment completion. Please try again"
    redirect_to profile_path(locale: I18n.locale,username: @education.user.username)
  end

  private

  	# Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit!
    end

    def branch_educations(branches)
      branches.each do |branch|
        educations = branch.educations.merge(BranchConnect.if_checked)
        educations_running = educations.running(session[:country])
        
        if params["education_type"].present?
          education_types = educations.collect(&:education_types).flatten.uniq.collect(&:id)
          params["education_type"].each do |education_type|
            @educations << educations_running if education_types.include? education_type.to_i
          end
        else
          @educations << educations_running
        end
      end
    end
end

app/views/educations/_education.html.erb
<div class="col-md-3">
	<% cache education do %>
  	<%= education.web_link.present? ? link_to(image_tag(education.image.url(:medium), :class=>"img-responsive index_box_image"), education.web_link) : image_tag(education.image.url(:medium), :class=>"img-responsive index_box_image") %>	
  <% end %>
	
</div>

app/views/educations/_form.html.erb
<%= form_for(@education, url: (@education.new_record? ? educations_path : education_path(I18n.locale, @education)) , multipart: true, :html=> {:class=>"education_form"}) do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :title, t(:title) %><br>
    <%= f.text_field :title, required: true, :class=>"form-control", :placeholder=>"Title of the education" %>
  </div>

  <div class="row">
    <div class="col-md-4 form-group">
      <%= f.label :web_link %><br>
      <%= f.text_field :web_link, :class=>"form-control", :placeholder=>"Provide Your Products Web link" %>
      <p class="web_url error_message"></p>
    </div>

    <div class="col-md-4 form-group">
      <%= f.label :start_date %><br>
      <%= f.text_field :start_date, required: true, :class=>"form-control datepicker_main calculate_amount", :placeholder=>"Start Date" %>
    </div>
    <div class="col-md-4 form-group">
      <%= f.label :end_date %><br>
      <%= f.text_field :end_date, required: true, :class=>"form-control datepicker_main calculate_amount", :placeholder=>"End Date" %>
      <p class="date-warning error_message"></p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="form-group">
        <h4>Select Type of your education </h4>
        <p class="education_type-warning error_message"></p>
        <%= f.fields_for(:education_connects) do |ff| %>
          <%= ff.hidden_field :education_type_id, value: ff.object.education_type_id %>
          <%= ff.check_box :checked , :class=>"education_checkbox" %> <%= ff.object.education_type.name %>
        <% end %>
      </div>
      <div class="form-group">
        <h4>Select Branch For this education </h4>
        <p class="branch-warning error_message"></p>
        <%= f.fields_for(:branch_connects) do |ff| %>
          Institute Name : <%= ff.object.branch.branchable.name %><br/>
          <%= ff.hidden_field :branch_id, value: ff.object.branch_id %>
          <%= ff.check_box :checked, :class=>"branch_checkbox" %> <%= ff.object.branch.name %><br/>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <br/>
      <div class="upload-preview">
        <% if @education.id.present? %>
          <%= image_tag @education.image.url(:medium), :style=>"height: 140px; width: 90%;" %>
        <% else %>
          <%= image_tag "missing.png", :style=>"height: 140px; width: 90%;" %>
        <% end %>
      </div>
      <% if @education.id.present? %>
        <%= f.file_field :image %>
      <% else %>
        <%= f.file_field :image, required: true %>
      <% end %>
    </div>
  </div>

  <%= hidden_field_tag "amount" %>
  
  <div class="actions">
    <%= f.submit :class=>"btn btn-success create_education" %>
  </div>
<% end %>


<script>

  $('.education_form').submit(function(){
    
    education_type = $(".education_checkbox").is(":checked");
    branch = $(".branch_checkbox").is(":checked");

    startDate = $("#education_start_date").val();
    endDate = $("#education_end_date").val();
    web_link=$("#education_web_link").val();    

    if (!education_type){
      $('.education_type-warning').html('Please select at least one education Type.');
      return false;
    }
    else{
      $('.education_type-warning').html('');
    }

    if (!branch){
      $('.branch-warning').html('Please select at least one branch.');
      return false;
    }
    else{
      $('.branch-warning').html('');
    } 

    // weblink validation
    if (web_link == "" || isUrl(web_link)){
      $('.web_url').html("");
    }else{
      $('.web_url').html("Not a valid url.");
      return false;
    }  
    // date picker validation
    if ((Date.parse(startDate) >= Date.parse(endDate))) {
      $('.date-warning').html('End date should be greater than Start date');
      return false;
    }
  })

  var preview = $(".upload-preview img");
  $("#education_image").change(function(event){
     var input = $(event.currentTarget);
     var file = input[0].files[0];
     var reader = new FileReader();
     reader.onload = function(e){
         image_base64 = e.target.result;
         preview.attr("src", image_base64);
     };
     reader.readAsDataURL(file);
  });


// url validation method
  function isUrl(s) {
    var regexp = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/
    return regexp.test(s);
  }

  $(".calculate_amount").change(function(){
    if( ($("#education_start_date").val() != "") && ($("#education_end_date").val() != "") && (($("input[name='education_type[]']:checked").val() != undefined)) ){

      var days = (daydiff(parseDate($('#education_start_date').val()), parseDate($('#education_end_date').val())) + 1);

      var total = 0
      $("input[name='education_type[]']:checked").each(function(){
        total += parseInt(this.id.split("_")[1])
      })
      total = days*total
      // $(".create_education").val("Create Education for $"+total)
      $(".create_education").val("Create Education")
      $("#amount").val(total)
    }
  })

  function parseDate(str) {
    var mdy = str.split('-')
    return new Date(mdy[0], mdy[1]-1, mdy[2]);
  }

  function daydiff(first, second) {
    return (second-first)/(1000*60*60*24);
  }

</script>

app/views/educations/_index_list.html.erb
<br>
<%= link_to 'New education', new_education_path(locale: I18n.locale) , :class=>"btn btn-info pull-right" if user_signed_in? && (current_user.is_admin || @user == current_user) %>
<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th></th>
      <% if @user.is_admin %><th><%= t(:owner) %></th> <% end %>
      <th><%= t(:title) %></th>
      <th><%= t(:web_link) %></th>
      <th><%= t(:start_date) %></th>
      <th><%= t(:end_date) %></th>
      <th><%= t(:institute) %></th>
      <th>Education Type</th>
      <th><%= t(:status) %></th>
      <% if (user_signed_in? && (current_user.is_admin || (@educations.collect(&:user).include? current_user))) %><th></th><% end %>
    </tr>
  </thead>

  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= image_tag education.image.url(:tiny) %></td>
        <% if @user.is_admin %><td> <%= link_to education.user.name, profile_path(locale: I18n.locale,username: education.user.username) %> </td> <% end %>
        <td><%= link_to education.title %></td>
        <td><%= link_to education.web_link, education.web_link %></td>
        <td><%= education.start_date %></td>
        <td><%= education.end_date %></td>
        <td><% education.branches.merge(branch_connect_checked).collect(&:branchable).uniq.each do |s| %>
            <%= link_to s.name, institute_path(s, locale: I18n.locale) %> <br/>
          <% end %>
        </td>
        <td><%= raw education.education_types.merge(EducationConnect.if_checked).collect(&:name).join("<br/>") %></td>
        <td><%= education.expired? ? "Expired" : "Running" %></td>
        <% if user_signed_in? && (current_user.is_admin || education.user == current_user) %>
          <td>
            <%= link_to t(:edit), edit_education_path(education, locale: I18n.locale) %>
            <%= link_to t(:destroy), [education, locale: I18n.locale], method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/educations/edit.html.erb
<h1>Editing education</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_path(locale: I18n.locale,:username => @education.user.username), :class=>"btn btn-default"  %>

app/views/educations/index.html.erb
<div class="load">
  <%= image_tag "loading.gif" %>
</div>

<div class="row">
  <div class="col-md-3">
    <div class="panel-group" id="accordion">
      <% @categories.each do|category, sub_categories| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <%= link_to category.name, educations_path(locale: I18n.locale, category_id: category.id), remote: true, :class=> "category_search" %>
              <a data-toggle="collapse" data-parent="#accordion" href="#category_<%= category.id %>" style="float:right">
                <%= image_tag "down_arrow.png", :class=>"down_arrow" %>
              </a>
            </h4>
          </div>
          <div id="category_<%= category.id %>" class="panel-collapse collapse">
            <div class="panel-body">
              <ul class="list-group">
            <% sub_categories.each do |sub_category| %>
              <li class="list-group-item">
                <%= link_to sub_category.name, educations_path(locale: I18n.locale, sub_category_id: sub_category.id), remote: true, :class=> "category_search"%>
              </li>
            <% end %>
          </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="filter_box">
      <%= form_tag educations_path(locale: I18n.locale), :method=> "get", :class=>"filter_form", remote: true do %>
        <h4><%= t(:filter_by) %> : </h4>
        <h5><%= t(:institute) %></h5><%= text_field_tag "institute_id" %><br/>
        <h5><%= t(:city) %></h5><%= text_field_tag "city", "", :class=>"form-control" %><br/>
        <h5>ZIP</h5><%= text_field_tag "zip", "", :class=>"form-control" %><br/>
        <h5>Type</h5>
        <% EducationType.all.limit(4).each do |education_type| %>
          <% if params["education_type"] %>
            <%= check_box_tag "education_type[]", education_type.id, params["education_type"][0].to_i ==education_type.id  ? true : false %>
          <% else %>
            <%= check_box_tag "education_type[]", education_type.id %>
          <% end %>
          <%= education_type.name %><br/>
        <% end %>
        <%= submit_tag t(:submit), :class=>"btn btn-success" %>
      <% end %>
    </div>
  </div>
  <div class="col-md-9">
    <div class="row" >
      <div class="education_block">
        <%= render @educations %>
      </div>
    </div>
    <% if !@educations.next_page.nil? %>
      <div class="load-more-container">
        <%= image_tag "loading1.gif", style: "display:none;", class: "loading-gif" %>
        <%= link_to t(:load_more), educations_path(locale: I18n.locale, page: 2), class: "btn btn-primary btn-lg adv-load-more" %>
      </div>
    <% end %>
  </div>
</div>


<script>
  $(".filter_form").submit(function(){
    if (($("#institute_id").val() != "") || ($("#city").val() != "") || ($("#zip").val() != "") || ($("#education_type_").val() != "") ){
      $(".load").show()
    }
  })

  $(".category_search").click(function(){
    $(".load").show()
  })

  $(function() {
    $("#institute_id").tokenInput("/get_institute.json", {
      tokenLimit: 1
    });
    $("#city").tokenInput("/get_city.json", {
      tokenLimit: 1
    });
    $("#zip").tokenInput("/get_zip.json", {
      tokenLimit: 1
    });
  });

  $(document).ready(function () {
    // when the load more link is clicked
    $('a.adv-load-more').click(function () {
      $('.adv-load-more').hide();
      $('.loading-gif').show();

      $.ajax({
        type: "GET",
        url: $(this).attr('href'),
        dataType: "script"
      });
      return false;
    });
  });

</script>

app/views/educations/index.js.erb
$(".load").hide();
var page = <%= params[:page].present? ? params[:page] : 1 %>

var category_id = "<%= params[:category_id].present? ? params[:category_id] : '' %>"
var sub_category_id = "<%= params[:sub_category_id].present? ? params[:sub_category_id] : '' %>"
var institute_id = "<%= params[:institute_id].present? ? params[:institute_id] : '' %>"

var education_type = "<%= params[:education_type].present? ? params[:education_type].join(',') : '' %>"
var zip = "<%= params[:zip].present? ? params[:zip] : '' %>"
var city = "<%= params[:city].present? ? params[:city] : '' %>"


<% if params[:page].present? %>
	$('.education_block').append('<%= j render @educations %>')
<% else %>
	$(".education_block").html("<%= j render @educations %>");
<% end %>

$("a.adv-load-more").attr("href", "/educations?page="+(page+1)+"&category_id="+category_id+"&sub_category_id="+sub_category_id+"&institute_id="+institute_id+"&education_type="+education_type+"&zip="+zip+"&city="+city )
$( ".filter_form input" ).prop( "disabled", false );

// show our load more link
$('.loading-gif').hide();

<% if !@educations.next_page.nil? %>
	$('.adv-load-more').show();
<% else %>
	$('.adv-load-more').hide();
<% end %>

app/views/educations/new.html.erb
<div class="jumbotron">
	<h2>New education</h2>

	<%= render 'form' %>

	<%= link_to 'Back', profile_path(locale: I18n.locale,:username => current_user.username), :class=>"btn btn-default"  %>
</div>