config/routes.rb
Rails.application.routes.draw do

  resources :templates
  get "/templates/new/:type" => "templates#new", as: "new_template_type"

  scope "(:locale)", locale: /en|sp|fr/ do
    devise_for :users

    resources :coupen_types, :deal_types, :education_types, :sale_types, :coupens, :banners, :zones

    resources :categories do 
      resources :sub_categories
    end

    resources :institutes do
      resources :branches
    end

    resources :stores do
      resources :branches
    end

    resources :tutorials do
      member do
        get 'complete_order'
      end
    end

    resources :sales do
      member do
        get 'complete_order'
      end
    end

    resources :video_advs do
      member do
        get 'complete_order'
      end
    end

    resources :flyers do
      member do
        get 'complete_order'
      end
    end

    resources :educations do
      member do
        get 'complete_order'
      end
    end

    resources :deals do
      member do
        get 'complete_order'
      end
    end

    resources :advertisements do
      member do
        get 'complete_order'
      end
    end

    get 'home/index'
    get 'search/result' => "home#search_result"
    get '/modal/:id/:model' => "home#data_modal", as: "data_modal"
    post '/mail/:id/:model' => "home#data_emailable", as: "data_emailable"

    post 'search/result' => "home#search_result"
    get '/category_sub' => 'home#category_sub'
    get '/get_store' => 'home#get_store'
    get '/get_institute' => 'home#get_institute'
    get '/get_zone' => 'home#get_zone'
    get '/get_city' => 'home#get_city'
    get '/get_zip' => 'home#get_zip'
    get '/users' => 'home#users'
    get '/block_user/:id' => 'home#block_user', as: "block_user"
    get '/slider/update_content' => 'slider#update_content', as: "update_slider_content"
    get '/session/change_country' => 'home#change_session_country'
    

    get "/:id" => "stores#show", as: "store_show"
    get 'user/:username' => "home#profile", as: "profile"
  end
  get '/:locale' => 'home#index'
  root 'home#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
	belongs_to :user

	has_many :branch_connects, as: :connectable
	has_many :branches, through: :branch_connects
	accepts_nested_attributes_for :branch_connects

	has_many :sale_connects, dependent: :destroy
	has_many :sale_types, :through => :sale_connects
	accepts_nested_attributes_for :sale_connects

	has_many :transactions, :as => :purchasable, dependent: :destroy

	has_attached_file :image, :styles => {:thumbnail => "550x380>",:medium => "300x300>", :tiny=>"50x50>" }, :default_url => "missing.png"
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  	scope :running, lambda {|country| where("start_date <= ? AND end_date >= ?", Date.today, Date.today).order(ActiveRecord::Base.connection.instance_values["config"][:adapter] == "mysql2" ? "RAND()" : "RANDOM()").joins(:branches).where("branches.country"=> country) }

  	def self.all_sub_categories
  		all.collect(&:branches).flatten.uniq.collect(&:branchable).uniq.collect(&:sub_categories).flatten.uniq
  	end

  	def expired?
		self.end_date < Date.today
	end
  	
end

app/models/sale_type.rb
class SaleType < ActiveRecord::Base
	has_many :sale_connects, dependent: :destroy
	has_many :sales, :through => :sale_connects

	translates :name
	default_scope { includes(:translations) }
	
	default_scope { order('id') }
	
	def sales_within_today(country)
		self.sales.merge(SaleConnect.if_checked).running(country)
	end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy, :complete_order]

  def index
    @sales = Sale.running(session[:country])
    @categories = @sales.all_sub_categories.group_by(&:category)
    

    if params["category_id"].present? || params["sub_category_id"].present?
      stores = params["category_id"].present? ? Category.find(params["category_id"]).get_stores : SubCategory.find(params["sub_category_id"]).stores
      @sales = stores.collect(&:branches).flatten.collect{ |b| b.sales.running(session[:country])}
    elsif params["store_id"].present?
      @sales = []
      store = Store.find(params["store_id"])
      branches = (params["city"].present? || params["zip"].present?) ? store.branches.in_location(params) : store.branches
      branch_sales(branches)
    elsif params["city"].present? || params["zip"].present?
      @sales = []
      branches = Branch.in_location(params)
      branch_sales(branches)
    elsif params["sale_type"].present?
      @sales = []
      params["sale_type"] = params["sale_type"].split(",") if !params["sale_type"].kind_of?(Array) 
      params["sale_type"].each do |sale_type|
        @sales << SaleType.find(sale_type).sales.merge(DealConnect.if_checked).running(session[:country])
      end
    end

    @sales = @sales.flatten.uniq.paginate(:page => params[:page], :per_page => 12)
  end

  def new
    @sale = Sale.new
    SaleType.all.each do |a|
      @sale.sale_connects.build(sale_type_id: a.id)
    end
    current_user.stores.collect(&:branches).flatten.each do |branch|
      @sale.branch_connects.build(branch_id: branch.id)
    end
    redirect_to new_store_path(locale: I18n.locale), notice: "You first have to create a Store before creating banner" if current_user.stores.blank?
  end


  def create
    @sale = current_user.sales.create(sale_params)    
    @sale.transactions.create(user_id: @sale.user_id, amount: params[:amount], currency: "USD", status: "pending")
    # base_url = (Rails.env == "development") ? 'http://localhost:3000' : 'http://www.etcty.com'

    # @response = EXPRESS_GATEWAY.setup_purchase((params[:amount].to_i*100),
    #   return_url: base_url+complete_order_sale_path(@sale, locale: I18n.locale) ,
    #   cancel_return_url: base_url,
    #   currency: "USD"
    # )

    # redirect_to EXPRESS_GATEWAY.redirect_url_for(@response.token)    
    redirect_to complete_order_sale_path(@sale, locale: I18n.locale)
  end

  def edit
  end

  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to profile_path(locale: I18n.locale,username: @sale.user.username), notice: 'Advertisement was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(locale: I18n.locale,username: @sale.user.username), notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def complete_order
    # response = EXPRESS_GATEWAY.purchase((@sale.transactions[0].amount)*100, {:token => params[:token],:payer_id => params[:PayerID]})
    # @sale.transactions[0].update_attributes(paypal_token: params[:token], paypal_payer_id: params[:PayerID])
    @sale.transactions[0].update_attributes(status: "paid")

    # if response.success?
    #   @sale.transactions[0].update_attributes(status: "paid")
    # end
    # flash[:sucess] = response.success? ? "Congratulations, your sale has been created" : "Oops!! Problem with the payment completion. Please try again"
    redirect_to profile_path(locale: I18n.locale,username: @sale.user.username)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit!
    end

    def branch_sales(branches)
      branches.each do |branch|
        sales = branch.sales.merge(BranchConnect.if_checked)
        sale_types = sales.collect(&:sale_types).flatten.uniq.collect(&:id)
        if params["sale_type"].present?
          params["sale_type"].each do |sale_type|
            @sales << sales.running(session[:country]) if sale_types.include? sale_type.to_i
          end
        else
          @sales << sales.running(session[:country])
        end
      end
    end

end

app/views/sales/_form.html.erb
<%= form_for(@sale, url: (@sale.new_record? ? sales_path : sale_path(I18n.locale, @sale)) , multipart: true, :html=> {:class=>"sale_form"}) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :title, t(:title) %><br>
    <%= f.text_field :title, required: true, :class=>"form-control", :placeholder=>"Title of the sale" %>
  </div>

  <div class="row">
    <div class="col-md-4 form-group">
      <%= f.label :web_link %><br>
      <%= f.text_field :web_link, :class=>"form-control", :placeholder=>"Provide Your Products Web link" %>
      <p class="web_url error_message"></p>
    </div>

    <div class="col-md-4 form-group">
      <%= f.label :start_date %><br>
      <%= f.text_field :start_date, required: true, :class=>"form-control datepicker_main calculate_amount", :placeholder=>"Start Date" %>
    </div>
    <div class="col-md-4 form-group">
      <%= f.label :end_date %><br>
      <%= f.text_field :end_date, required: true, :class=>"form-control datepicker_main calculate_amount", :placeholder=>"End Date" %>
      <p class="date-warning error_message"></p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <div class="form-group">
        <h4>Select Type of your sale </h4>
        <p class="sale_type-warning error_message"></p>
        <%= f.fields_for(:sale_connects) do |ff| %>
          <%= ff.hidden_field :sale_type_id, value: ff.object.sale_type_id %>
          <%= ff.check_box :checked , :class=>"sale_checkbox" %> <%= ff.object.sale_type.name %>
        <% end %>
      </div>
      <div class="form-group">
        <h4>Select Branch For this sale </h4>
        <p class="branch-warning error_message"></p>
        <%= f.fields_for(:branch_connects) do |ff| %>
          Store Name : <%= ff.object.branch.branchable.name %><br/>
          <%= ff.hidden_field :branch_id, value: ff.object.branch_id %>
          <%= ff.check_box :checked, :class=>"branch_checkbox" %> <%= ff.object.branch.name %><br/>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <br/>
      <div class="upload-preview">
        <% if @sale.id.present? %>
          <%= image_tag @sale.image.url(:medium), :style=>"height: 140px; width: 90%;" %>
        <% else %>
          <%= image_tag "missing.png", :style=>"height: 140px; width: 90%;" %>
        <% end %>
      </div>
      <% if @sale.id.present? %>
        <%= f.file_field :image %>
      <% else %>
        <%= f.file_field :image, required: true %>
      <% end %>
    </div>
  </div>

  <%= hidden_field_tag "amount" %>

  <div class="actions">
    <%= f.submit :class=>"btn btn-success create_sale" %>
  </div>
<% end %>


<script>

  $('.sale_form').submit(function(){
    
    sale_type = $(".sale_checkbox").is(":checked");
    branch = $(".branch_checkbox").is(":checked");
    
    startDate = $("#sale_start_date").val();
    endDate = $("#sale_end_date").val();
    web_link=$("#sale_web_link").val();    

    if (!sale_type){
      $('.sale_type-warning').html('Please select at least one sale Type.');
      return false;
    }
    else{
      $('.sale_type-warning').html('');
    }

    if (!branch){
      $('.branch-warning').html('Please select at least one branch.');
      return false;
    }
    else{
      $('.branch-warning').html('');
    } 

    // weblink validation
    if (web_link == "" || isUrl(web_link)){
      $('.web_url').html("");
    }else{
      $('.web_url').html("Not a valid url.");
      return false;
    }  
    // date picker validation
    if ((Date.parse(startDate) >= Date.parse(endDate))) {
      $('.date-warning').html('End date should be greater than Start date');
      return false;
    }
  })

  var preview = $(".upload-preview img");
  $("#sale_image").change(function(event){
     var input = $(event.currentTarget);
     var file = input[0].files[0];
     var reader = new FileReader();
     reader.onload = function(e){
         image_base64 = e.target.result;
         preview.attr("src", image_base64);
     };
     reader.readAsDataURL(file);
  });


// url validation method
  function isUrl(s) {
    var regexp = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/
    return regexp.test(s);
  }

  $(".calculate_amount").change(function(){
    if( ($("#sale_start_date").val() != "") && ($("#sale_end_date").val() != "") && (($("input[name='sale_type[]']:checked").val() != undefined)) ){

      var days = (daydiff(parseDate($('#sale_start_date').val()), parseDate($('#sale_end_date').val())) + 1);

      var total = 0
      $("input[name='sale_type[]']:checked").each(function(){
        total += parseInt(this.id.split("_")[1])
      })
      total = days*total
      // $(".create_sale").val("Create sale for $"+total)
      $(".create_sale").val("Create sale")
      $("#amount").val(total)
    }
  })

  function parseDate(str) {
    var mdy = str.split('-')
    return new Date(mdy[0], mdy[1]-1, mdy[2]);
  }

  function daydiff(first, second) {
    return (second-first)/(1000*60*60*24);
  }

</script>

app/views/sales/_index_list.html.erb
<br>

<%= link_to 'New Sale', new_sale_path(locale: I18n.locale) , :class=>"btn btn-info pull-right" if user_signed_in? && (current_user.is_admin || @user == current_user) %>
<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th></th>
      <% if @user.is_admin %><th><%= t(:owner) %></th> <% end %>
      <th><%= t(:title) %></th>
      <th><%= t(:web_link) %></th>
      <th><%= t(:start_date) %></th>
      <th><%= t(:end_date) %></th>
      <th><%= t(:store) %></th>
      <th>Sale Type</th>
      <th><%= t(:status) %></th>
      <% if (user_signed_in? && (current_user.is_admin || (@sales.collect(&:user).include? current_user))) %><th></th><% end %>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= image_tag sale.image.url(:tiny) %></td>
        <% if @user.is_admin %><td> <%= link_to sale.user.name, profile_path(locale: I18n.locale,username: sale.user.username) %> </td> <% end %>
        <td><%= link_to sale.title %></td>
        <td><%= link_to sale.web_link, sale.web_link %></td>
        <td><%= sale.start_date %></td>
        <td><%= sale.end_date %></td>
        <td><% sale.branches.merge(branch_connect_checked).collect(&:branchable).uniq.each do |s| %>
            <%= link_to s.name, store_show_path(s, locale: I18n.locale) %> <br/>
          <% end %>
        </td>
        <td><%= raw sale.sale_types.merge(SaleConnect.if_checked).collect(&:name).join("<br/>") %></td>
        <td><%= sale.expired? ? "Expired" : "Running" %></td>
        <% if user_signed_in? && (current_user.is_admin || sale.user == current_user) %>
          <td>
            <%= link_to t(:edit), edit_sale_path(sale, locale: I18n.locale) %>
            <%= link_to t(:destroy), [sale, locale: I18n.locale], method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/_sale.html.erb
<div class="col-md-3">
  <% cache sale do %>
  	<%= link_to(image_tag(sale.image.url(:medium), :class=>"img-responsive index_box_image"), sale.web_link)%>	
  <% end %>
</div>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

app/views/sales/index.html.erb
<div class="load">
	<%= image_tag "loading.gif" %>
</div>

<div class="row">
	<div class="col-md-3">
		<div class="panel-group" id="accordion">
			<% @categories.each do|category, sub_categories| %>
			  <div class="panel panel-default">
			    <div class="panel-heading">
			      <h4 class="panel-title">
			        <%= link_to category.name, sales_path(locale: I18n.locale, category_id: category.id), remote: true, :class=> "category_search" %>
			        <a data-toggle="collapse" data-parent="#accordion" href="#category_<%= category.id %>" style="float:right">
			        	<%= image_tag "down_arrow.png", :class=>"down_arrow" %>
			        </a>
			      </h4>
			    </div>
			    <div id="category_<%= category.id %>" class="panel-collapse collapse">
			      <div class="panel-body">
			        <ul class="list-group">
						<% sub_categories.each do |sub_category| %>
						  <li class="list-group-item">
						    <%= link_to sub_category.name, sales_path(locale: I18n.locale, sub_category_id: sub_category.id), remote: true, :class=> "category_search"%>
						  </li>
						<% end %>
					</ul>
			      </div>
			    </div>
			  </div>
			<% end %>
		</div>

		<div class="filter_box">
			<%= form_tag sales_path(locale: I18n.locale), :method=> "get", :class=>"filter_form", remote: true do %>
				<h4><%= t(:filter_by) %> : </h4>
				<h5><%= t(:store) %></h5><%= text_field_tag "store_id" %><br/>
				<h5><%= t(:city) %></h5><%= text_field_tag "city", "", :class=>"form-control" %><br/>
				<h5>ZIP</h5><%= text_field_tag "zip", "", :class=>"form-control" %><br/>
				<h5>Type</h5>
				<% SaleType.all.limit(4).each do |sale_type| %>
					<% if params["sale_type"] %>
						<%= check_box_tag "sale_type[]", sale_type.id, params["sale_type"][0].to_i ==sale_type.id  ? true : false %>
					<% else %>
						<%= check_box_tag "sale_type[]", sale_type.id %>
					<% end %>
					<%= sale_type.name %><br/>
				<% end %>
				<%= submit_tag t(:submit), :class=>"btn btn-success" %>
			<% end %>
		</div>
	</div>
	<div class="col-md-9">
		<div class="row" >
	      <div class="sale_block">
	        <%= render @sales %>
	      </div>
	    </div>
	    <% if !@sales.next_page.nil? %>
	      <div class="load-more-container">
	        <%= image_tag "loading1.gif", style: "display:none;", class: "loading-gif" %>
	        <%= link_to t(:load_more), sales_path(locale: I18n.locale, page: 2), class: "btn btn-primary btn-lg adv-load-more" %>
	      </div>
	    <% end %>
	</div>
</div>


<script>
	$(".filter_form").submit(function(){
		if (($("#store_id").val() != "") || ($("#city").val() != "") || ($("#zip").val() != "") || ($("#sale_type_").val() != "") ){
			$(".load").show()
		}
	})

	$(".category_search").click(function(){
		$(".load").show()
	})

	$(function() {
    $("#store_id").tokenInput("/get_store.json", {
    	tokenLimit: 1
    });
    $("#city").tokenInput("/get_city.json", {
    	tokenLimit: 1
    });
    $("#zip").tokenInput("/get_zip.json", {
    	tokenLimit: 1
    });
  });

	
  $(document).ready(function () {
    // when the load more link is clicked
    $('a.adv-load-more').click(function () {
      $('.adv-load-more').hide();
      $('.loading-gif').show();

      $.ajax({
        type: "GET",
        url: $(this).attr('href'),
        dataType: "script"
      });
      return false;
    });
  });

</script>

app/views/sales/index.js.erb
$(".load").hide();
var page = <%= params[:page].present? ? params[:page] : 1 %>

var category_id = "<%= params[:category_id].present? ? params[:category_id] : '' %>"
var sub_category_id = "<%= params[:sub_category_id].present? ? params[:sub_category_id] : '' %>"
var store_id = "<%= params[:store_id].present? ? params[:store_id] : '' %>"

var sale_type = "<%= params[:sale_type].present? ? params[:sale_type].join(',') : '' %>"
var zip = "<%= params[:zip].present? ? params[:zip] : '' %>"
var city = "<%= params[:city].present? ? params[:city] : '' %>"


<% if params[:page].present? %>
	$('.sale_block').append('<%= j render @sales %>')
<% else %>
	$(".sale_block").html("<%= j render @sales %>");
<% end %>

$("a.adv-load-more").attr("href", "/sales?page="+(page+1)+"&category_id="+category_id+"&sub_category_id="+sub_category_id+"&store_id="+store_id+"&sale_type="+sale_type+"&zip="+zip+"&city="+city )
$( ".filter_form input" ).prop( "disabled", false );

// show our load more link
$('.loading-gif').hide();

<% if !@sales.next_page.nil? %>
	$('.adv-load-more').show();
<% else %>
	$('.adv-load-more').hide();
<% end %>

app/views/sales/new.html.erb
<h1>New sale</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_path(locale: I18n.locale,:username => current_user.username), :class=>"btn btn-default"  %>